### ISSUE TITLE
analysis ready working site data for SPC and tow

### ISSUE THREAD

**Issue by adelheenan** [splboyle/cred_fish#3]
Hi Shannon - so I have updated the SPC working site data file to exclude sharks and jacks and have created the tow level data, with total large fish biomass, shark and jack biomass and abundance. 

The following files in the data folder are what you should work with:

SPC DATA:
TMPwsd.Rdata 
2009-2016 SPC data, all sites (including forereef, backreef, lagoon), excluding sharks and jacks, total fish biomass, parrotfish biomass, and the abundance and biomass per species. Each row is a site and includes the wave data (see the previous issue / comment).

TOW DATA:
TMP FishTow_Mean_family_tow_level_ABUND / BIO
2000-2015, all tow (excluding tows less than 10 m, or greater than 20 m, forereef only), total large fish abundance / biomass (two separate csv files), and the biomass per family (Carangidae and Carcharhinidae for jacks and sharks).

I also created island per year mean estimates - and there are two versions of each file, one with the mean and one with the standard error for abundance and biomass. I'll do the same later for the SPC data but will wait till a decision is made on whether we will report at the georegion with island, or island level.

I think is all you need for now - if not let me know.

Cheers, Adel

**Comment by splboyle** [comment]
Hi Adel, 
Does this mean that I would exclude sharks and jacks from the wave energy analysis? It seems to me that all species/biomass should be included for that analysis. Am I mistaken?
Thanks for all this!
Shannon

**Comment by adelheenan** [comment]
Yes - it's not ideal really. Here are a couple of options:

1) run it with the SPC data only - but twice with and without the sharks and jacks

2) run it with the SPC and the tow data separately - but this would require estimating wave exposure from the tows - and I am not sure how we'd go about this. One simple but rough way would be to use the tow centre point lat long and ask Jeanette to estimate wave exposure for those lat longs - but she might also have a better idea on how to estimate across the tow length. The latter would be the best option but probably a longer term project - so perhaps not viable for this instance. Maybe check in with her when she is back, for now I reckon go ahead with option 1.
