### ISSUE TITLE
regression tree models

### ISSUE THREAD

**Issue by adelheenan** [splboyle/cred_fish#4]
Hi Shannon,

I have some code for fitting random forests and gradient forests, which are methods to identify threshold levels in drivers on ecological variables via BRTs

Before I share it with you (I need to clean it up) - you should take a read of this article:

http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0119922

I got the code from the authors of this paper and edited it so it is good to go and ready to work on with our site level data. 

This could be an analytical option - however, lets chat once you've read it, and we can weigh up the relative gains of this more complex approach - which can come at the cost of ease of explanation to readers of the report.

Also when we chat, if you haven't figured out this already, lets get you set up to create summaries in markdown of your analysis - to avoid computer crashing issues in future.

Adel

**Comment by splboyle** [comment]
Sounds good - will do. Let's chat tomorrow or Friday? 

I have never used markdown but would love to learn. I've heard a lot about it and it seems very useful. 

Thanks, 
Shannon

**Comment by adelheenan** [comment]
Ok - good. I am around tomorrow, or we could meet at UH on Friday (I work from there on Fridays).

**Comment by splboyle** [comment]
Today is good - I will catch you before you leave.

**Comment by splboyle** [comment]
Hey Adel, let me know when you have a moment to chat.

**Comment by adelheenan** [comment]
Hi Shannon,

I have uploaded some random forest code in the scr folder - this should run on the site level data - also you will need the functions that are in gradForestFunc - which are in the lib folder.

Cheers, Adel

**Comment by splboyle** [comment]
Thanks Adel. 

I'm having trouble loading the forest packages. I am getting this error:
`Loading required package: gradientForest
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘gradientForest’`

for both.. I've tried installing them alone and am unsure how to proceed. It seems like my version of R may be too recent. Any suggestions? I'm going to workshop right now for 30 min but will be back and may try on my work computer to see if it works on that.

**Comment by adelheenan** [comment]
Ah yes - I had the same issue... I ended up having to install an older version of R - and because my mac os wasn't compatible with the version I wanted, I worked on the windows side which did have back compatibility. So depending on how new your mac is, the best option might be the windows machine.

**Comment by splboyle** [comment]
My computer is just about a year old so I doubt it will be compatible. I'll work on the windows. Thanks.
