### ISSUE TITLE
Temporary SPC data files

### ISSUE THREAD

**Issue by adelheenan** [splboyle/cred_fish#6]
Hi Shannon - I  have created the summary metrics for total fish biomass, biomass per consumer group and parrotfishes (these are separated by large and small, but you can just add them together to get all parrotfish biomass).

There are two new files in the data folder:

tmp_RAMP_BASICdata_pooled_is_yr_RZ.rdata (all islands by year and reef type)

tmp_RAMP_BASICdata_pooled_island.rdata (all islands pooled across years by reef type)

These are 2010 onwards, SPC only, no filtering of outliers has been done. The structure of the data files are listed, with the first element a dataframe of means and the second element of the SE. Plan on replacing these temporary files once we have the 2016 data ready to work with. We could also discuss capping the outliers at that stage too.

Let me know if you have any questions - hopefully all is clear!

Adel

**Comment by splboyle** [comment]
Hey Adel - if I'm doing everything correctly, I think that the data in both of those files are the same. Neither of them seem to have the years - both are pooled across years. Are you seeing this as well?

**Comment by adelheenan** [comment]
Hi Shannon - yes you are doing everything correctly - I just saved the same file type twice by accident. I'll upload the correct version that has metrics per year.

Sorry about that! Adel
